### PR TITLE
Parse whole number and negative timestamps

### LINKED ISSUE #3073: Serde fails to parse a server timestamp if it's a whole number
This came up in tests, when I passed a `modified` time of 0, but I imagine we could also get "lucky" and fail in production if the server happens to commit a record on a whole millisecond boundary.

I think the only thing we need to do is train our [`TimestampVisitor`](https://github.com/mozilla/application-services/blob/e1daa2a7e9add66c5a36a7c967495510c2e117e8/components/support/sync15-traits/src/server_timestamp.rs#L80-L96) to visit integer types as well as floats.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1230)
┆Story Points: 1
┆Sprint: SYNC - end 2020-05-22

### PR DESCRIPTION
**Pull request by kaylagalway**
### Pull Request checklist ###

Fixes #3073 

- [x] **Quality**: This PR builds and tests run cleanly
  - `automation/all_tests.sh` runs to completion and produces no failures
  - Note: For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/master/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

**Comment by linacambridge** [comment]
@kaylagalway Aaaaah, Clippy is being a stickler! 📎🔥 [Clippy](https://github.com/rust-lang/rust-clippy) is a Rust linter that has more elaborate checks than the warnings in `cargo check`. It integrates with Cargo, so you can run `cargo clippy` after installing it!

File: components/support/sync15-traits/src/server_timestamp.rs [hunk 1]
```diff
@@ -87,11 +87,23 @@ impl<'de> serde::de::Visitor<'de> for TimestampVisitor {
...
+    fn visit_i64<E: serde::de::Error>(self, value: i64) -> Result<Self::Value, E> {
+        Ok(if value < 0 {
+            ServerTimestamp(0)
+        } else {
+            ServerTimestamp(value * 1000)
+        })
+    }
+
+    fn visit_u64<E: serde::de::Error>(self, value: u64) -> Result<Self::Value, E> {
+        Ok(ServerTimestamp(value as i64 * 1000))
```
Comment (thomcc) [inline components/support/sync15-traits/src/server_timestamp.rs:100]: Hmm... Should we be using `checked_mul` and `i64::try_from` for these? If we're seeing weird values it might be worth it...

File: components/support/sync15-traits/src/server_timestamp.rs [hunk 2]
```diff
@@ -118,8 +130,16 @@ mod test {
...
+        // test deserialize of float
         let ts: ServerTimestamp = serde_json::from_str(&ser).unwrap();
         assert_eq!(ServerTimestamp(123_456), ts);
+
+        // test deserialize of whole number
+        let ts: ServerTimestamp = serde_json::from_str("123").unwrap();
+        assert_eq!(ServerTimestamp(123_000), ts);
+
+        // test deserialize of negative number
+        let ts: ServerTimestamp = serde_json::from_str("-123").unwrap();
```
Comment (thomcc) [inline components/support/sync15-traits/src/server_timestamp.rs:142]: Did these tests fail before the change? (If so: that's really surprising, what a footgun!)

File: components/support/sync15-traits/src/server_timestamp.rs [hunk 3]
```diff
@@ -90,8 +90,8 @@ impl<'de> serde::de::Visitor<'de> for TimestampVisitor {
 }
 
 impl<'de> serde::de::Deserialize<'de> for ServerTimestamp {
```
Comment (linacambridge) [inline components/support/sync15-traits/src/server_timestamp.rs:92]: Sorry, one more thing—would you mind deleting `TimestampVisitor`, since we've replaced it with `f64::deserialize`? Thanks!

Comment (kaylagalway) [reply components/support/sync15-traits/src/server_timestamp.rs:92]: Yeah np!
