### PR TITLE
Ignore remote logins that we cannot parse. 

### LINKED ISSUE #1253: Lockwise shows "no logins" when there's an unparseable login on the server
Based on slack conversation, we *think* this was happening to Ryan Gaddis.  He was able to sign in to the Lockwise app and it would *claim* to sync his logins, but would display "no logins" in the UI even though he actually had plenty of logins stored in his account, and other Firefoxes could see and sync then just fine.

He then deleted his synced logins, and uploaded some fresh ones, and Lockwise is now able to sync and display them.

So IIUC the theory is, there was a corrupt or otherwise unexpected login record on the server somewhere, that existing Firefoxes could parse just fine but that our rust component couldn't. This caused us to fail to sync any logins down locally.

@thomcc does this seem accurate based on slack conversation?

If so, some scoping questions:

* Is it expected that we would fail to sync anything in the face of a single badly-formed record in the collection?
* Would this show up as a "sync failed" erorr that the Lockwise app should be catching and showing special UI for?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-15)
┆Story Points: 1
┆Sprint: SYNC - 2019-07-05
┆Epic: Lockwise Support

### PR DESCRIPTION
**Pull request by thomcc**
Fixes #1253

I also added getters for the EngineIncoming fields, and doc comments on the setters.

### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - `cargo test --all` produces no test failures
  - `cargo clippy --all --all-targets --all-features` runs without emitting any warnings
  - `cargo fmt` does not produce any changes to the code
  - `./gradlew ktlint detekt` runs without emitting any warnings
  - `swiftformat --swiftversion 4 megazords components/*/ios && swiftlint` runs without emitting any warnings or producing changes
  - Note: For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/master/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

File: components/logins/src/db.rs [hunk 1]
```diff
@@ -183,7 +184,15 @@ impl LoginDb {
...
                 }
                 seen_ids.insert(incoming.0.id.clone());
-                sync_data.push(SyncLoginData::from_payload(incoming.0.clone(), incoming.1)?);
+                match SyncLoginData::from_payload(incoming.0.clone(), incoming.1) {
+                    Ok(v) => sync_data.push(v),
+                    Err(e) => {
+                        log::error!("Failed to deserialize record {:?}: {}", incoming.0.id, e);
+                        // Ideally we'd track new_failed, but it's unclear how
+                        // much value it has.
+                        telem.failed(1);
```
Comment (linacambridge) [inline components/logins/src/db.rs]: Hmm, it would be nice if we had a way to report non-fatal errors like this, so we could see what it's doing. Something for Sentry, if we ever integrate it into Rust?

Comment (thomcc) [reply components/logins/src/db.rs]: I agree, it would be nice if there were a better way to report this. That said, we can probably investigate this if it turns out that we see a lot of `failed` for logins. (This is the only thing that writes that).
