### PR TITLE
Move places reset methods to PlacesApi

### LINKED ISSUE #2667: Cannot sync bookmarks on Firefox iOS
When using the "Rust FxA" branch of Firefox iOS, I'm getting the following when trying to sync:

```
[RUST][ffi_support::handle_map] HandleMap access with handle having wrong map id: Handle { map_id: 39227, version: 2, index: 0 } (our map id is 39228)
```

After some investigation I've concluded that `resetBookmarkSyncMetadata` should not take an `API` handle but a `Connection` one.
What's very strange about this is that the `master` branch of Firefox iOS does not show this behaviour, despite calling the same FFI function with the same wrong handle (and the presumed bug has been present for month).

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-845)
┆Story Points: 5
┆Sprint: SYNC - end 2020-02-28

### PR DESCRIPTION
**Pull request by eoger**
Fixes #2667.

### CODE REVIEW

**Comment by thomcc** [comment]
My feeling is that this should be on PlacesApi, as otherwise it can be called during a sync. That said, in https://github.com/mozilla/application-services/commit/c2fdfc85e61aeb4c96be10e2f27afcf6d6f35c8d#diff-1d157ec195946881dc83a97db5fb09bf @linacambridge explicitly moved it *from* placesapi to the write connection... But I'm not sure why. @linacambridge Do you happen to remember any context here?

**Comment by linacambridge** [comment]
Oh yikes, I'm sorry about that! I think I moved it because I wasn't sure what would happen on disconnect—`resetBookmarkSyncMetadata` should be called after signing out, when I guess the sync connection would already be closed—but I think I was just confused. Should we expose both `reset` methods on `PlacesApi` only, and have them use the separate connection even if Sync isn't set up?

File: components/places/ffi/src/lib.rs [hunk 1]
```diff
@@ -480,17 +480,17 @@ pub extern "C" fn places_accept_result(
 #[no_mangle]
 pub extern "C" fn places_reset(handle: u64, error: &mut ExternError) {
     log::debug!("places_reset");
-    CONNECTIONS.call_with_result(error, handle, |conn| -> places::Result<_> {
-        storage::history::history_sync::reset(conn)?;
+    APIS.call_with_result(error, handle, |api| -> places::Result<_> {
+        api.reset_history()?;
```
Comment (eoger) [inline components/places/ffi/src/lib.rs]: We call `reset_history` instead of `storage::history::history_sync::reset`, does that look ok to you @linacambridge ? It seems like it roughly does the same thing.

Comment (thomcc) [reply components/places/ffi/src/lib.rs]: I'd kind of like @linacambridge to weigh in here before landing

Comment (eoger) [reply components/places/ffi/src/lib.rs]: Yup it does

**Comment by eoger** [comment]
> Looks good, does this fix #2667?

Yup can confirm
