### PR TITLE
Prefer rusqlite::Row::get_checked() over rusqlite::Row::get(), fixes #462

### LINKED ISSUE #462: Replace all rusqlite row.get() calls with row.get_checked()
Via a slack discussion - row.get() will panic if it fails. In some cases the only reason it would fail is db corruption, but even then, it's better we get an Err() than a panic.

### PR DESCRIPTION
**Pull request by mhammond**
I hope I got this right. There's only 1 left in components/logins/examples/sync_pass_sql.rs, which I didn't bother fixing.

### CODE REVIEW

File: components/places/src/api/history.rs [hunk 1]
```diff
@@ -60,9 +60,9 @@ mod tests {
     use super::*;
 
     #[test]
-    fn test_insert() {
-        let mut c = PlacesDb::open_in_memory(None).expect("should get a connection");
-        let url = Url::parse("http://example.com").expect("it's a valid url");
+    fn test_insert() -> Result<()> {
+        let mut c = PlacesDb::open_in_memory(None)?;
```
Comment (thomcc) [inline components/places/src/api/history.rs]: Last time I tried this, writing the tests in this way removed line numbers from panics. That makes it much harder to track down which assert/expect/unwrap fired. Is that still true?

Comment (mhammond) [reply components/places/src/api/history.rs]: Ouch - it does remove them :( I reverted that.
