### PR TITLE
Fix sendtab mobile type enums

### LINKED ISSUE #1163: Device is registered with type=DESKTOP, even though type=MOBILE is specified
`Mobile` device type is passed into `initializeDevice`, but the current device record I see afterwards say that device is DESKTOP.

cc @eoger @vladikoff

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-43)
┆Story Points: 3
┆Sprint: SYNC - 2019-07-05
┆Epic: Fenix 2.0 Support

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #1163

### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - `cargo test --all` produces no test failures
  - `cargo clippy --all --all-targets --all-features` runs without emitting any warnings
  - `cargo fmt` does not produce any changes to the code
  - `./gradlew ktlint detekt` runs without emitting any warnings
  - `swiftformat --swiftversion 4 megazords components/*/ios && swiftlint` runs without emitting any warnings or producing changes
  - Note: For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
- [ ] ~~**Tests**: This PR includes thorough tests or an explanation of why it does not~~
Testing manually via Fenix
- [x] **Changelog**: This PR includes a changelog entry or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/master/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

File: components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/Device.kt [hunk 1]
```diff
@@ -40,11 +40,8 @@ data class Device(
                 }
             }
         }
-
-        fun toNumber(): Int {
-            return MsgTypes.Device.Type.DESKTOP.number
-        }
```
Comment (rfk) [inline components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/Device.kt]: Technically a breaking API change since we're removing this method?

File: components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/FirefoxAccount.kt [hunk 2]
```diff
@@ -400,7 +400,7 @@ class FirefoxAccount(handle: FxaHandle, persistCallback: PersistCallback?) : Aut
         val (nioBuf, len) = capabilitiesToBuffer(supportedCapabilities)
         rustCall { e ->
             val ptr = Native.getDirectBufferPointer(nioBuf)
-            LibFxAFFI.INSTANCE.fxa_initialize_device(this.handle.get(), name, deviceType.toNumber(), ptr, len, e)
+            LibFxAFFI.INSTANCE.fxa_initialize_device(this.handle.get(), name, deviceType.ordinal, ptr, len, e)
```
Comment (eoger) [inline components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/FirefoxAccount.kt]: I believe this is the wrong fix, we should keep (and fix) `toNumber` instead using these values: https://github.com/mozilla/application-services/blob/77bd14de63df6b3d974e97dd069fb94e6929526f/components/fxa-client/src/fxa_msg_types.proto#L41-L45 (a comment to this line wouldn't hurt either).

Comment (vladikoff) [reply components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/FirefoxAccount.kt]: Sounds good!
