### PR TITLE
bug: stop eating errors, allow verifyConnection() without subscriptions

### LINKED ISSUE #873: Use less clever error handling within Push FFI
Push FFI is currently eating rust errors. Be less "clever" and make sure exceptions are passed up.

### PR DESCRIPTION
**Pull request by jrconlin**
* FFI layer was eating rust exceptions, those are now passed on
* allowing `verifyConnection()` after PushManager create so client can
  write simple bootstrapping code
* Now checking prior subscription status for other calls.

BREAKING CHANGE
* the argument `socket_protocol` is now `http_protocol` to correctly map
  it's role. `socket_protocol` will be used later for desktop websocket
  connections

Closes #873, #874

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - `cargo test --all` produces no test failures
  - `cargo clippy --all --all-targets --all-features` runs without emitting any warnings
  - `cargo fmt` does not produce any changes to the code
  - `./gradlew ktlint detekt` runs without emitting any warnings
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly

### CODE REVIEW

**Comment by jrconlin** [comment]
@thomcc I think your original r- was lost from the original PR. Sorry about that.

File: components/push/ffi/src/lib.rs [hunk 1]
```diff
@@ -140,14 +140,12 @@ pub extern "C" fn push_update(handle: u64, new_token: FfiStr<'_>, error: &mut Ex
...
-            if !r {
-                if let Ok(new_endpoints) = mgr.regenerate_endpoints() {
-                    // use a `match` here to resolve return of <_>
-                    return serde_json::to_string(&new_endpoints).map_err(|e| {
-                        push_errors::ErrorKind::TranscodingError(format!("{:?}", e)).into()
-                    });
-                }
+        if !mgr.verify_connection()? {
+            let new_endpoints = mgr.regenerate_endpoints()?;
+            if new_endpoints.is_empty() {
```
Comment (thomcc) [inline components/push/ffi/src/lib.rs]: Is this correct? The condition looks backwards to me.

File: components/push/ffi/src/lib.rs [hunk 2]
```diff
@@ -186,15 +184,15 @@ pub extern "C" fn push_dispatch_for_chid(
...
-            Ok(String::from(""))
+        match mgr.get_record_by_chid(chid)? {
+            Some(record) => {
+                let dispatch = json!({
+                    "uaid": record.uaid,
+                    "scope": record.scope,
+                });
+                Ok(dispatch.to_string())
+            }
+            None => Ok(String::from("")),
```
Comment (thomcc) [inline components/push/ffi/src/lib.rs]: We should really be handling None the way every other FFI layer handles it (e.g. as null pointer and not as an empty string)...

But we can get to that later.

File: components/push/ffi/src/lib.rs (hunk 1 above)
Comment (jrconlin) [reply components/push/ffi/src/lib.rs]: Ah, good catch! messed it up while doing the clippy fix. Looks like testing caught it too.

File: components/push/ffi/src/lib.rs (hunk 2 above)
Comment (jrconlin) [reply components/push/ffi/src/lib.rs]: Good point. May try to address it here if it's not terrible.

Comment (jrconlin) [reply components/push/ffi/src/lib.rs]: Hrm, not sure how to deal with the Option<Result<String>> in the `callRust` layer. Don't want to block either while I try to figure it out.

Comment (thomcc) [reply components/push/ffi/src/lib.rs]: Feel free to file a follow up and I'll try and get to it when I have time. I have a good idea of what's required and it's not totally trivial.

Comment (jrconlin) [reply components/push/ffi/src/lib.rs]: filed #877
