### PR TITLE
Document how we plan to manage writes to sqlite and a wip sketch

### LINKED ISSUE #394: Flesh out a strategy for history to deal with sqlite locking/busy errors and avoiding blocking during long operations
There are some cases where we expect sqlite to fail with SQLITE_BUSY. In the general case, we should be able to guard against and/or recover from these errors without dropping any data and without the app being aware.

Also, the ffi layer will ensure only 1 thread is in our rust code at once. Even without locking issues, we can't afford to block all threads while a sync is in progress as some may take many many seconds.

### LINKED ISSUE #515: Decide how to manage concurrent Places connections for syncing and storing bookmarks
On Desktop, we use a cloned Places connection and an attached database. Could we instead have a single database, with separate connections for the UI (the main Places connection), and Sync?

That would also let us register `TEMP` triggers on each connection, so that we could use triggers for tombstones, like @thomcc suggested, and share non-`TEMP` triggers across the connections. This could be tricky for triggers that involve `TEMP` tables, but tractable.

For bookmarks, Desktop also has a [`totalSyncChanges` counter](https://bugzilla.mozilla.org/show_bug.cgi?id=1472963) to avoid keeping a transaction open for the entire merge, and aborting if the in-memory local tree no longer matches what's in the database. Is there a better approach?

### PR DESCRIPTION
**Pull request by mhammond**
This documents the dilemma we find ourselves in when trying to serialize all sql writers when one of those writers is sync. The doc also proposes a solution and sketches out what that might look like. I'm guessing everyone will hate the name of the new rust object (I do!) so I assume that will need to be changed, and if we go down this route the doc should change so it reads less like a proposal and more like documentation for a decision.

I'm flagging for review in the hope it's noticed by everyone, although as above, I don't intend merging in its current state even if everyone approves of the idea.

WDYT?

Closes #394. Closes #515.

### CODE REVIEW

File: components/support/sql/src/conn_ext.rs [hunk 1]
```diff
@@ -213,3 +217,72 @@ impl<'conn> ConnExt for UncheckedTransaction<'conn> {
...
+            tx: UncheckedTransaction::new(conn, behavior)?,
+            behavior,
+            commit_after,
+        })
+    }
+
+    /// Checks to see if we have held a transaction for longer than the
+    /// requested time, and if so, commits the current transaction and opens
+    /// another.
+    pub fn maybe_commit(&mut self) -> SqlResult<()> {
```
Comment (thomcc) [inline components/support/sql/src/conn_ext.rs]: I wonder if we should organize this so that maybe_commit is called from Deref::deref... Then again, that's probably more trouble than it's worth...

File: components/support/sql/src/conn_ext.rs [hunk 2]
```diff
@@ -213,3 +217,72 @@ impl<'conn> ConnExt for UncheckedTransaction<'conn> {
...
+    commit_after: Duration,
+}
+
+impl<'conn> TransactionForPerf<'conn> {
+    /// Begin a new transaction which may be split into multiple transactions
+    /// for performance reasons. Cannot be nested, but this is not
+    /// enforced; use a rusqlite `savepoint` for nested transactions.
+    pub fn new(
+        conn: &'conn Connection,
+        behavior: TransactionBehavior,
```
Comment (thomcc) [inline components/support/sql/src/conn_ext.rs]: I wonder if we should consider enforcing this dynamically (e.g. by checking if a transaction is open somehow). That would avoid a TransactionForPerf committing a correctness transaction accidentally...

File: components/support/sql/src/conn_ext.rs [hunk 3]
```diff
@@ -213,3 +217,72 @@ impl<'conn> ConnExt for UncheckedTransaction<'conn> {
...
+    /// Consumes and rolls back an unchecked transaction.
+    pub fn rollback(self) -> SqlResult<()> {
+        self.tx.rollback()
+    }
+}
+
+impl<'conn> Deref for TransactionForPerf<'conn> {
+    type Target = Connection;
+
+    fn deref(&self) -> &Connection {
```
Comment (thomcc) [inline components/support/sql/src/conn_ext.rs]: nit: this is probably worth `#[inline]`ing.

File: components/support/sql/src/conn_ext.rs [hunk 4]
```diff
@@ -213,3 +217,72 @@ impl<'conn> ConnExt for UncheckedTransaction<'conn> {
...
+            behavior,
+            commit_after,
+        })
+    }
+
+    /// Checks to see if we have held a transaction for longer than the
+    /// requested time, and if so, commits the current transaction and opens
+    /// another.
+    pub fn maybe_commit(&mut self) -> SqlResult<()> {
+        if self.tx.started_at.elapsed() >= self.commit_after {
```
Comment (thomcc) [inline components/support/sql/src/conn_ext.rs]: In the future it might be worth putting the body of this (e.g. what we do if the time is elapsed) in an #[inline(never)] function, and then inline the rest of this function (but this is only likely to matter if it starts getting called inside tight loops or something).

File: components/support/sql/src/conn_ext.rs (hunk 1 above)
Comment (thomcc) [reply components/support/sql/src/conn_ext.rs]: It's fine as is.

File: components/support/sql/src/conn_ext.rs (hunk 2 above)
Comment (thomcc) [reply components/support/sql/src/conn_ext.rs]: You can do this using https://docs.rs/rusqlite/*/rusqlite/struct.Connection.html#method.is_autocommit. We should also probably do this in UncheckedTransaction too...

File: components/places/doc/sql_concurrency.md [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+
+* If we use a single writer thread we would use a single-transaction for sync - but even this leaves writes blocked for a very long time (and includes time on the network). ie, writes may have *very* high latency, may never complete if the app is terminated - but would never experience `SQLITE_BUSY`.
+
+* If we allowed multiple writer threads, we would use a transaction-per-record for sync, meaning both threads would almost certainly complete in their timeout budget - although the sync would take many many minutes to complete.
+
+So how about a compromise: we use 2 writer threads, but:
+
+* One is dedicated to the small and fast writes (eg, a visit, creation of a bookmark, etc).
+
+* One is dedicated to Sync, but it uses a strategy whereby we use these "performance transactions", but only for a set period of time. For example, when processing 5k records, we use one transaction per (say) 1000ms. We squeeze as many of the 5k records as we can into this time period and commit and start a new transaction as necessary.
```
Comment (linacambridge) [inline components/places/doc/sql_concurrency.md]: It's also possible, though maybe inadvisable, for the small writer to preempt the Sync connection on `SQLITE_BUSY`, by calling `sqlite3_interrupt` on the Sync connection. As you pointed out on Slack, it's not immediate, but it will cancel pending reads and roll back transactions...which is fine for Sync! At that point, we know we're syncing stale data, anyway, so we can abort and try the sync again once the main writer finishes.

File: components/support/sql/src/conn_ext.rs [hunk 6]
```diff
@@ -110,6 +110,10 @@ pub trait ConnExt {
     fn unchecked_transaction(&self) -> SqlResult<UncheckedTransaction> {
         UncheckedTransaction::new(self.conn(), TransactionBehavior::Deferred)
     }
+
+    fn perf_transaction(&self, commit_after: Duration) -> SqlResult<TransactionForPerf> {
```
Comment (linacambridge) [inline components/support/sql/src/conn_ext.rs]: You were right, I'm not the biggest fan of the name. 😂 Maybe `TimeChunkedTransaction`, `TimeSliceTransaction`, `RolledUpTransaction`, or something that makes it clear we're possibly rolling up multiple transactions into one based on time. _Wanders off to paint her bikeshed_ 🚲🎨🏠

File: components/support/sql/src/conn_ext.rs [hunk 7]
```diff
@@ -213,3 +217,72 @@ impl<'conn> ConnExt for UncheckedTransaction<'conn> {
         &*self
     }
 }
+
+/// This transaction is suitable for when a transaction is being used only
+/// for performance when updating a larger number of rows (ie, when the
+/// transaction is not necessary for data integrity). You can specify a
```
Comment (linacambridge) [inline components/support/sql/src/conn_ext.rs]: I think it's OK for integrity, too, as long as you don't call `maybe_commit` until you're actually ready to commit? As in, if you have a sequence of operations like:

```txt
WRITE A
WRITE B
MAYBE COMMIT
WRITE C
WRITE D
MAYBE COMMIT
```

We might commit (A, B) and (C, D) in two different transactions, or we might commit (A, B, C, D) in one. But you should only call `maybe_commit` after (A, B) if you're OK with either being interrupted after, or other readers seeing (A, B) without you having written (C, D). If that's not OK, you should wait to call `maybe_commit` until you've written (C, D), too...with the caveat that this might take longer than `commit_after`, and lose the advantage of using a `TransactionForPerf` over a vanilla `UncheckedTransaction`.

IOW, assume that `maybe_commit` will _always_ commit, and treat the fact that it doesn't, and might roll up multiple transactions in one, as an optimization...which is, indeed, why `TransactionForPerf` exists!

File: components/support/sql/src/conn_ext.rs [hunk 8]
```diff
@@ -213,3 +217,72 @@ impl<'conn> ConnExt for UncheckedTransaction<'conn> {
...
+/// duration for the maximum amount of time the transaction should be held.
+/// You should regularly call .maybe_commit() as part of your processing, and
+/// if the current transaction has been open for greater than the specified
+/// duration the transaction will be committed and another one started.
+/// You should always call .commit() at the end. Note that if you call
+/// .rollback() at the end, only the current transaction will be rolled back.
```
Comment (linacambridge) [inline components/support/sql/src/conn_ext.rs]: On the one hand, I could see this being surprising, and maybe we shouldn't expose a way to roll the transaction back explicitly. On the other, SQLite might roll it back implicitly (due to a constraint violation, invalid SQL, app crash, power loss, interrupt, etc.), so we don't gain much by hiding it. The warning about "don't call `maybe_commit` unless you're really ready to commit" is probably enough.

File: components/support/sql/src/conn_ext.rs (hunk 2 above)
Comment (linacambridge) [reply components/support/sql/src/conn_ext.rs]: Hmm, how could `TransactionForPerf` commit a correctness transaction accidentally? SQLite returns an error if you try to start a nested transaction, so, IIUC, `UncheckedTransaction::new` will fail?

File: components/support/sql/src/conn_ext.rs [hunk 9]
```diff
@@ -213,3 +217,72 @@ impl<'conn> ConnExt for UncheckedTransaction<'conn> {
...
+    }
+
+    /// Checks to see if we have held a transaction for longer than the
+    /// requested time, and if so, commits the current transaction and opens
+    /// another.
+    pub fn maybe_commit(&mut self) -> SqlResult<()> {
+        if self.tx.started_at.elapsed() >= self.commit_after {
+            self.tx.conn.execute_batch("COMMIT")?;
+            log::debug!("Transaction commited after taking allocated time");
+            self.tx = UncheckedTransaction::new(self.tx.conn, self.behavior)?;
```
Comment (linacambridge) [inline components/support/sql/src/conn_ext.rs]: Hmm, I feel uneasy about committing the transaction out from under the `UncheckedTransaction` here.

Why not use a `Cell<Option<UncheckedTransaction>>` to store `tx`, so that we can consume `self.tx` here (`self.tx.take().unwrap().commit()`, but with better error handling), then `self.tx.set(Some(UncheckedTransaction::new(...)?))` to store the new transaction back in the cell. That way, if we fail to start a new transaction because another writer beat us to it, we won't hold on to the (now-stale) `UncheckedTransaction` in `tx`. And we could then return errors if you try to `commit` or `rollback` when we don't have a `tx`, instead of silently committing or rolling back whatever's in progress.

Do you think that might work?

File: components/places/doc/sql_concurrency.md (hunk 5 above)
Comment (mhammond) [reply components/places/doc/sql_concurrency.md]: Interesting! One thing that worries me with this is that Sync may end up being interrupted most of the time while the app is being used (ie, that if a user was actually browsing and accumulating visits, sync would always be killed.) This means Sync will continually be doing (possibly significant) work before being killed and needing to do it again.

However, if we could arrange for it to happen only when the small writer would actually get SQLITE_BUSY it might make sense. I wonder if we could abuse sqlite3_busy_handler here?

File: components/support/sql/src/conn_ext.rs (hunk 9 above)
Comment (thomcc) [reply components/support/sql/src/conn_ext.rs]: You could do this without the Cell<Option> with `std::mem::swap`. E.g.
```rust
let mut tx = UncheckedTransaction::new(...);
std::mem::swap(&mut self.tx, &mut tx);
tx.commit()?;
```

File: components/support/sql/src/conn_ext.rs (hunk 7 above)
Comment (thomcc) [reply components/support/sql/src/conn_ext.rs]: Hm, that makes sense to me, and I hadn't thought about it like this.

File: components/support/sql/src/conn_ext.rs (hunk 2 above)
Comment (thomcc) [reply components/support/sql/src/conn_ext.rs]: Ah, you're right.

File: components/support/sql/src/conn_ext.rs (hunk 7 above)
Comment (mhammond) [reply components/support/sql/src/conn_ext.rs]: > I think it's OK for integrity, too

I need to think about rewording this, but the pedant in me thinks your example *is* just about perf. Eg, 
```
BEGIN IMMEDIATE
WRITE A
WRITE B
WRITE C
WRITE D
COMMIT
```

when you could COMMIT between B and C, but choose not to, you are probably making that choice based on performance.

I do understand your point though, so I'll try and make that clearer in the comments.

File: components/support/sql/src/conn_ext.rs [hunk 10]
```diff
@@ -213,3 +233,95 @@ impl<'conn> ConnExt for UncheckedTransaction<'conn> {
...
+    }
+
+    /// Checks to see if we have held a transaction for longer than the
+    /// requested time, and if so, commits the current transaction and opens
+    /// another.
+    #[inline]
+    pub fn maybe_commit(&mut self) -> SqlResult<()> {
+        if self.tx.started_at.elapsed() >= self.commit_after {
+            log::debug!("TimeChunkedTransaction commiting after taking allocated time");
+            self.commit_and_start_new_tx()?;
```
Comment (grigoryk) [inline components/support/sql/src/conn_ext.rs]: IIUC, at the core of wanting to release a transaction early is a concern around resource contention. That is, you have others wanting to acquire write access and do some work, and they can't.

With that in mind, would it make sense to not just restart a transaction now and then, but also wait for a certain amount of time to give others a chance to do their writes? E.g. have a "delay before restart" configuration param and invoke sleep on the current thread for that amount of time.

Otherwise, that time frame is implicit and is mostly determined by what's going on while we're in between `maybe_commit` calls.

Comment (thomcc) [reply components/support/sql/src/conn_ext.rs]: SQLite should take care of some of that for us, and if it doesn't I still strongly feel that invoking sleep() is a bad solution. If it comes to this, we have the ability to coordinate explicitly.
