### PR TITLE
Workaround protobuf bug

### LINKED ISSUE #3053: Protobuf crashes in v0.58.1
See https://github.com/mozilla-mobile/fenix/issues/10277 for context.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1200)
┆Sprint: Backlog

### PR DESCRIPTION
**Pull request by eoger**
The should fix the Android 5 issue reported in https://github.com/mozilla-mobile/fenix/issues/10277 (fixes #3053 also).
However because the fix to the above involves upgrading to 3.11.4, this would resurrect the bug we had earlier in https://github.com/mozilla/application-services/issues/3032, so I also fixed this one in a different way.

I'm going to make review comments to explain what I did here.

### CODE REVIEW

File: components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt [hunk 1]
```diff
@@ -47,13 +48,18 @@ open class RustBuffer : Structure() {
 
     fun asCodedInputStream(): CodedInputStream? {
         return this.data?.let {
-            CodedInputStream.newInstance(it.getByteBuffer(0, this.len))
+            if (this.len < Int.MIN_VALUE || this.len > Int.MAX_VALUE) {
+                throw RuntimeException("len does not fit in a int")
+            }
+            CodedInputStream.newInstance(it.getByteArray(0, this.len.toInt()))
```
Comment (eoger) [inline components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt:54]: Here we avoid using the `ByteBuffer` constructor of `CodedInputStream` since it ends up creating a [buggy implementation](https://github.com/protocolbuffers/protobuf/blob/e667bf6eaaa2fb1ba2987c6538df81f88500d030/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L185-L187).

File: components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt [hunk 2]
```diff
@@ -47,13 +48,18 @@ open class RustBuffer : Structure() {
...
         }
     }
 
     fun asCodedOutputStream(): CodedOutputStream? {
         return this.data?.let {
-            CodedOutputStream.newInstance(it.getByteBuffer(0, this.len))
+            val method = CodedOutputStream::class.java.getDeclaredMethod("newSafeInstance", ByteBuffer::class.java)
+            method.isAccessible = true
+            return method.invoke(null, it.getByteBuffer(0, this.len)) as CodedOutputStream
```
Comment (eoger) [inline components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt:62]: We do the same here, by [forcing the usage](https://github.com/protocolbuffers/protobuf/blob/e667bf6eaaa2fb1ba2987c6538df81f88500d030/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L130-L140) of `newSafeInstance`

File: components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt (hunk 1 above)
Comment (thomcc) [reply components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt:58]: That's unfortunate, as this requires an additional copy. We should fix this when possible...

File: components/viaduct/android/src/main/java/mozilla/appservices/httpconfig/HttpConfig.kt [hunk 3]
```diff
@@ -95,8 +96,8 @@ object RustHttpConfig {
                     }
                     rb
                 } catch (e: Throwable) {
-                    LibViaduct.INSTANCE.viaduct_log_error("Network error: ${e.message}")
-                    MsgTypes.Response.newBuilder().setExceptionMessage(e.message)
+                    LibViaduct.INSTANCE.viaduct_log_error("Network error: ${Log.getStackTraceString(e)}")
```
Comment (thomcc) [inline components/viaduct/android/src/main/java/mozilla/appservices/httpconfig/HttpConfig.kt:99]: Not opposed to this but does it have any PII concerns?

File: components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt (hunk 1 above)
Comment (eoger) [reply components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt:58]: Yup I opened a PR: https://github.com/protocolbuffers/protobuf/pull/7440

File: components/viaduct/android/src/main/java/mozilla/appservices/httpconfig/HttpConfig.kt (hunk 3 above)
Comment (eoger) [reply components/viaduct/android/src/main/java/mozilla/appservices/httpconfig/HttpConfig.kt:99]: It should be fine: it logs a classic Java stack trace (no parameters or any kind of PII as far as I saw).

Comment (grigoryk) [reply components/viaduct/android/src/main/java/mozilla/appservices/httpconfig/HttpConfig.kt:99]: Stacktraces could easily have PII embedded in an exception message, and the new version has a higher chance of hitting that, I think? Depending on how exactly stacktrace is printed out.

File: components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt (hunk 2 above)
Comment (grigoryk) [reply components/support/android/src/main/java/mozilla/appservices/support/native/RustBuffer.kt:69]: Ouch :/

**Comment by grigoryk** [comment]
Specifically, tested w/ an emulator and a FireHD tablet that runs Android 5.

File: components/viaduct/android/src/main/java/mozilla/appservices/httpconfig/HttpConfig.kt (hunk 3 above)
Comment (eoger) [reply components/viaduct/android/src/main/java/mozilla/appservices/httpconfig/HttpConfig.kt]: Reverted the file.
