### PR TITLE
Only flag frecency recalcs for bookmarks. Fixes #3566.

### LINKED ISSUE #3566: firefox fenix nightly - bookmarks not syncing
`sync_manager::manager: engine "bookmarks" status: Err(Error(Store error: Error executing SQL: FOREIGN KEY constraint failed))`

[log.txt](https://github.com/mozilla/application-services/files/5199254/log.txt)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1758)
┆Sprint: SYNC - end 2020-09-11

### PR DESCRIPTION
**Pull request by mhammond**
I think this is close to good, but I rushed a bit at the end and haven't self-reviewed properly yet - I'll have a more detailed look tomorrow, but might as well get feedback now.

### CODE REVIEW

File: components/places/src/bookmark_sync/store.rs [hunk 1]
```diff
@@ -2974,6 +2975,115 @@ mod tests {
...
+
+        incoming.changes.push((
+            Payload::from_json(remote_unfiled).unwrap(),
+            ServerTimestamp(0),
+        ));
+
+        let outgoing = store
+            .apply_incoming(vec![incoming], &mut telemetry::Engine::new("bookmarks"))
+            .expect("should apply");
+        let outgoing_ids = outgoing
```
Comment (linacambridge) [inline components/places/src/bookmark_sync/store.rs:3068]: Should we assert this is empty? (Is it actually empty?)

**Review by linacambridge — APPROVED** [review]
Terrific, thank you so much Mark! I’ll let you do a final spot check before merging, but this looks great to me 💯
