### PR TITLE
Bookmark records on the server might have 'dateAdded' as a string (fixes #1148)

### LINKED ISSUE #1148: Handle bookmark records containing string date added timestamps
@ckarlof showed me this interesting stack trace:

> 05-17 12:49:13.651  3234 12962 W sync15::sync_multiple: Store error: Error synchronizing: JSON error: invalid type: string "1520897319380", expected i64)
> 05-17 12:49:13.651  3234 12962 I sync15::sync_multiple: Updating persisted global state
> 05-17 12:49:13.653  3234 12962 E places::ffi: Unexpected error: SyncAdapterError(Error(
> 05-17 12:49:13.653  3234 12962 E places::ffi: 
> 05-17 12:49:13.653  3234 12962 E places::ffi: Store error: Error synchronizing: JSON error: invalid type: string "1520897319380", expected i64))
> 05-17 12:49:13.657  3234 17084 E StorageSync: Error synchronizing a bookmarks store
> 05-17 12:49:13.657  3234 17084 E StorageSync: mozilla.appservices.places.PlacesException: Error synchronizing: Store error: Error synchronizing: JSON error: invalid type: string "1520897319380", expected i64
> 05-17 12:49:13.657  3234 17084 E StorageSync: 	at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
> 05-17 12:49:13.657  3234 17084 E StorageSync: 	at mozilla.appservices.places.PlacesApi.syncBookmarks(PlacesConnection.kt:12)
> 05-17 12:49:13.657  3234 17084 E StorageSync: 	at mozilla.components.browser.storage.sync.RustPlacesConnection.syncBookmarks(Connection.kt:2)
> 05-17 12:49:13.657  3234 17084 E StorageSync: 	at mozilla.components.browser.storage.sync.PlacesBookmarksStorage$sync$2.invokeSuspend(PlacesBookmarksStorage.kt:3)
> 05-17 12:49:13.657  3234 17084 E StorageSync: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
> 05-17 12:49:13.657  3234 17084 E StorageSync: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
> 05-17 12:49:13.657  3234 17084 E StorageSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
> 05-17 12:49:13.657  3234 17084 E StorageSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:1)
> 05-17 12:49:13.657  3234 17084 E StorageSync: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:42)
> 05-17 12:49:13.657  3234 17084 I SyncWorker: Synchronized store history
> 05-17 12:49:13.657  3234 17084 E SyncWorker: Failed to synchronize store bookmarks

It looks like [our Android implementation](https://searchfox.org/mozilla-central/rev/0078b9e7d42c366b102d7aec918caf64fed1d574/mobile/android/services/src/main/java/org/mozilla/gecko/sync/repositories/domain/BookmarkRecord.java#189-196) handles both strings and numbers.

### PR DESCRIPTION
**Pull request by mhammond**
I think this handles exactly "dateAdded might be a string" and IIUC, that's all we care about here. It's obviously easy to extend this to other timestamp-like fields, but I'm not sure we should do that here (or even at all!)...

### CODE REVIEW

File: components/places/src/bookmark_sync/record.rs [hunk 1]
```diff
@@ -317,6 +322,48 @@ pub enum BookmarkItemRecord {
...
+fn de_maybe_stringified_timestamp<'de, D>(
+    deserializer: D,
+) -> std::result::Result<Option<i64>, D::Error>
+where
+    D: serde::de::Deserializer<'de>,
+{
+    use std::fmt;
+    use std::marker::PhantomData;
+
+    struct StringOrInt(PhantomData<Option<i64>>);
```
Comment (linacambridge) [inline components/places/src/bookmark_sync/record.rs]: What does `PhantomData` do here?

File: components/places/src/bookmark_sync/record.rs [hunk 2]
```diff
@@ -450,4 +497,74 @@ mod tests {
             })
         );
     }
+
+    // XXX - all below 'dateadded' tests only check the 'BookmarkItemRecord' variant.
+    // Is there a sane way to check all? Should we maybe have a specific type
+    // avoiding the need to remember `date_added: Option<i64>` needs the serde
+    // `deserialize_with` attribute?
```
Comment (linacambridge) [inline components/places/src/bookmark_sync/record.rs]: That's a good idea...since you're almost all the way there, we could make the `StringOrInt` type public, add a serializer (that always serializes as an integer), and maybe a `From<i64>` implementation.

File: components/places/src/bookmark_sync/record.rs [hunk 3]
```diff
@@ -450,4 +497,74 @@ mod tests {
...
+
+    #[test]
+    fn test_dateadded_str() {
+        check_date_added(
+            json!({"id": "unfiled", "parentid": "menu", "type": "bookmark", "dateAdded": "123"}),
+            Some(123),
+        )
+    }
+
+    // A kinda "policy" decision - like serde, 'type errors' fail rather than default.
```
Comment (linacambridge) [inline components/places/src/bookmark_sync/record.rs]: 👍 If we see anything else in the wild, we'll have Sentry or engine failure telemetry tell us.

File: components/places/src/bookmark_sync/record.rs (hunk 1 above)
Comment (mhammond) [reply components/places/src/bookmark_sync/record.rs]: It apparently allows the type to act like it holds an `Option<i64>` without actually holding one, and TBH, I copy-pasta'd this from other serde examples trying to do similar things.

If I remove that and change the deserialize call to `deserializer.deserialize_any(StringOrInt(Some(0)))` things work, which is both somewhat confusing and smelly. 🤷‍♂

File: components/places/src/bookmark_sync/record.rs (hunk 2 above)
Comment (mhammond) [reply components/places/src/bookmark_sync/record.rs]: FTR, based on our slack discussion, we decided to not do this.

File: components/places/src/bookmark_sync/record.rs (hunk 1 above)
Comment (thomcc) [reply components/places/src/bookmark_sync/record.rs]: PhantomData only would matter here if it were generic, or if Option<i64> implemented Drop, held onto references, or a couple other cases.

It doesn't really matter, though.
