### PR TITLE
 Use `sync-guid` in `sync15` and `logins`

### LINKED ISSUE #1395: Use `sync-guid` in `sync15` and `logins`
`logins` is an easy case, `sync15` is harder. `sync15` has a lot of places where we use sync ids:

- `id` field of a BsoRecord, Payload, ...
- `ids` in CollectionRequest
- lots of places talk about `failed_ids` and `successful_ids`
- sync_id in MetaGlobalRecord, MetaGlobalEngine
- `id` in CryptoKeysRecord (although it's always the string "keys")
- `records_synced` passed to `Store::sync_finished`
- both fields of `CollSyncIds`
- definitely more, I just skimmed.

However we also have things that are called an id, but are unrelated. Some rules of thumb for telling the cases apart:

- The tokenserver token, and related code has a few fields like id or uid... but that have nothing to do with sync ids.

- key_id/kid is a JWT thing and has nothing to do with sync ids.

- any place where we use the output of `random_guid` is definitely a sync id (in fact, that function should just be replaced with `Guid::random()` from #1394).

- Any place where we use a string to talk about a record is probably a guid. the exception is for cases where it's a JSON-serialized record, which it will be in a couple cases.

- If in doubt, either ask, or add logging statements into the sync15 crate and run the integration tests. If it's a 12-character base64url encoded string, it's almost certainly a sync id.

- If you really can't tell, err on the side of leaving it a string, as that's less potentially confusing in the future.

CC @lyuyuan92. It would be great if you took this if you're interested, but it's not a problem if you don't have time or would rather not.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-188)

### PR DESCRIPTION
**Pull request by lyuyuan**
fixes #1395

### CODE REVIEW

File: components/logins/examples/sync_pass_sql.rs [hunk 1]
```diff
@@ -212,7 +213,7 @@ fn show_all(engine: &PasswordEngine) -> Result<Vec<String>> {
                 timestamp_to_string(rec.time_last_used)
             }
         ]);
-        v.push(rec.id.clone());
+        v.push(rec.guid.as_str().to_owned());
```
Comment (thomcc) [inline components/logins/examples/sync_pass_sql.rs]: probably better to just store the guid in v, e.g. rec.guid.clone()

File: components/logins/src/login.rs [hunk 2]
```diff
@@ -8,12 +8,13 @@ use rusqlite::Row;
...
 use std::time::{self, SystemTime};
 use sync15::ServerTimestamp;
+use sync_guid::Guid;
 
 #[derive(Debug, Clone, Hash, PartialEq, Serialize, Deserialize, Default)]
 #[serde(rename_all = "camelCase")]
 pub struct Login {
-    // TODO: consider `#[serde(rename = "id")] pub guid: String` to avoid confusion
-    pub id: String,
+    #[serde(rename = "id")]
```
Comment (thomcc) [inline components/logins/src/login.rs]: Thanks for doing this at the same time!

File: components/sync15/src/request.rs [hunk 3]
```diff
@@ -69,7 +70,7 @@ impl CollectionRequest {
     where
         V: Into<Vec<String>>,
```
Comment (thomcc) [inline components/sync15/src/request.rs]: Changing this to V: Into<Vec<Guid>> is probably better.

**Comment by lyuyuan** [comment]
> I think Guid should implement From, so most of the as_str().into() seem unnecessary to me? Are they not?

Ah! You are right, I was being silly there. I will address these. Thanks for reviewing!

File: components/sync15/src/request.rs (hunk 3 above)
Comment (lyuyuan) [reply components/sync15/src/request.rs]: Do you mean changing it to `V: into<Vec<Guid>>`? The compiler says 1 type argument expected on `Vec`.

Comment (thomcc) [reply components/sync15/src/request.rs]: Whoops, github for some reason removed the inner brackets because it didn't have code quotes, sorry!

Comment (lyuyuan) [reply components/sync15/src/request.rs]: Done!

File: components/logins/examples/sync_pass_sql.rs (hunk 1 above)
Comment (lyuyuan) [reply components/logins/examples/sync_pass_sql.rs]: Done!

File: components/logins/examples/sync_pass_sql.rs [hunk 4]
```diff
@@ -229,7 +230,7 @@ fn prompt_record_id(e: &PasswordEngine, action: &str) -> Result<Option<String>>
         log::info!("No such index");
         return Ok(None);
     }
-    Ok(Some(index_to_id[input].clone()))
+    Ok(Some(index_to_id[input].as_str().into()))
```
Comment (lyuyuan) [inline components/logins/examples/sync_pass_sql.rs]: I have left this one as it is here, since it can't be moved out of borrowed.

Comment (thomcc) [reply components/logins/examples/sync_pass_sql.rs]: That's fine, the examples aren't as important anyway.

File: components/support/guid/src/lib.rs [hunk 5]
```diff
@@ -97,6 +102,32 @@ impl FastGuid {
     }
 }
 
+impl Ord for FastGuid {
```
Comment (thomcc) [inline components/support/guid/src/lib.rs]: Oh, yikes, nice catch with this bug.

That said, I'd prefer these be implemented on Guid and not FastGuid.

E.g. manually implement them all for Guid, deferring to `self.as_bytes()` (and not self.as_str() to avoid needing extra UTF-8 validation). That would also catch any cases where a guid that is small ends up in the non-FastGuid storage, not that that should ever happen.

Sorry, was taking a quick look through and missed this the first time.

File: components/support/guid/src/lib.rs [hunk 6]
```diff
@@ -315,6 +346,14 @@ impl fmt::Display for Guid {
     }
 }
 
+impl std::default::Default for Guid {
+    /// Create a default guid by calling `Guid::new("")`
+    #[inline]
+    fn default() -> Self {
+        Guid::new("")
```
Comment (thomcc) [inline components/support/guid/src/lib.rs]: Nit: `Guid::empty()` (and in doc comment).

Comment (lyuyuan) [reply components/support/guid/src/lib.rs]: Done!

File: components/support/guid/src/lib.rs (hunk 5 above)
Comment (lyuyuan) [reply components/support/guid/src/lib.rs]: Not sure if I get this correct this time. Please take a look, thanks!
