### PR TITLE
Fix logins strings issue

### LINKED ISSUE #623: [logins] LoginRecord objects never contain optional strings
In Swift, calling `get(id:)` returns an optional `LoginRecord`. There are properties on `LoginRecord` that are optional strings such as `formSubmitURL` and `httpRealm`. However, they are currently never optional. When no value is present, the properties are currently set to empty `""` strings. This becomes a bigger problem if you attempt to call `update(login:)` on a `LoginRecord` that was returned by the API since you get an error that you cannot supply both a `formSubmitURL` and an `httpRealm` at the same time.

### LINKED ISSUE #640: iOS error wrappers sometimes drop errors on the floor
When we moved to using handles, we forgot to change https://github.com/mozilla/application-services/blob/master/components/logins/ios/Logins/Errors/LoginStoreError.swift#L87 to handle that that guard may succeed but still indicate a problem.

This also seems to be true of methods that return nothing.

This is broken in logins and fxa.

Patch incoming.

### PR DESCRIPTION
**Pull request by thomcc**
I also hit #640, which had been mentioned but I hadn't realized was definitely still a thing. So I fixed it too.

Also the first commit cleans up a bunch of trailing whitespace because I hadn't realized it was there. Not sure how to make xcode not do that, but, well, eventually I'll look into it.

Fixes #623 
Fixes #640

### CODE REVIEW

**Comment by thomcc** [comment]
Rust test failures are #567 :(. Nothing we can do about it yet though.

File: components/logins/ios/Logins/LoginRecord.swift [hunk 1]
```diff
@@ -124,8 +123,8 @@ open class LoginRecord {
 
             username: dict["username"] as? String ?? "",
```
Comment (justindarc) [inline components/logins/ios/Logins/LoginRecord.swift]: Should we do the same for `username`? It is technically optional, but I'm not sure if there's a distinction with how an empty `username` gets stored to the DB.

Comment (thomcc) [reply components/logins/ios/Logins/LoginRecord.swift]: Ah, nice catch.

Comment (thomcc) [reply components/logins/ios/Logins/LoginRecord.swift]: For `username`, `username_field`, and `password_field`, it looks like empty strings are treated the same as nil. Which is... kind of dodgy. But yeah, it doesn't make a difference. I'll change them to be nil to reflect what actually comes over from rust though.

Comment (thomcc) [reply components/logins/ios/Logins/LoginRecord.swift]: (Actually, I don't think it's dodgy, I prefer empty strings to NULL in the DB, even if it's just because they work more predictably in comparisons. Anyway, this shouldn't have been exposed, that way, I'll make the change.)
