### PR TITLE
Have the Fennec places import handle null parents and invalid utf-8.

### LINKED ISSUE #2536: Tolerate NULL parents when importing bookmarks from Fennec
Fennec's `BrowserDB` has a [`FOREIGN KEY` constraint](https://searchfox.org/mozilla-esr68/rev/1f90a88b90290e330fc0fef8291f469e42712367/mobile/android/base/java/org/mozilla/gecko/db/BrowserDatabaseHelper.java#133,141,148-149) on `bookmarks.parent`, so all rows should reference existing parent. However, there's no `NOT NULL` constraint on that column, so Places roots and the [old mobile root](https://searchfox.org/mozilla-esr68/rev/1f90a88b90290e330fc0fef8291f469e42712367/mobile/android/base/java/org/mozilla/gecko/db/BrowserDatabaseHelper.java#1284-1287) might have `NULL` parents. But our [primary key on `moz_bookmarks_synced_structure`](https://github.com/mozilla/application-services/blob/master/components/places/sql/create_shared_schema.sql#L207-L210) doesn't allow this, since it implies `NOT NULL`.

We should handle these gracefully—in the case of the Places root, we make the parent be itself, in the case of other roots (including mobile), make the parent the Places root; for others, maybe move to unfiled?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-748)
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-02-28

### LINKED ISSUE #2607: PlacesException: Error executing SQL: Conversion error from type Text at index: 4
```
[INFO] mozilla.appservices.places.PlacesException: Error executing SQL: Conversion error from type Text at index: 4, invalid utf-8 sequence of 1 bytes from index 28
```

See https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6963672/ for details

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-804)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-02-28

### PR DESCRIPTION
**Pull request by mhammond**
Fixes #2536, fixes #2607.

### CODE REVIEW

File: components/places/src/import/fennec/bookmarks.rs [hunk 1]
```diff
@@ -303,11 +303,11 @@ lazy_static::lazy_static! {
...
         )
         SELECT
-            normalize_root_guid(b.guid),
+            normalize_root_guid(sanitize_utf8(b.guid)),
             b.type,
-            (SELECT normalize_root_guid(p.guid) FROM fennec.bookmarks p WHERE p._id = b.parent),
+            IFNULL((SELECT normalize_root_guid(sanitize_utf8(p.guid)) FROM fennec.bookmarks p WHERE p._id = b.parent), 'unfiled_____'),
             b.position,
-            b.title,
+            sanitize_utf8(b.title),
```
Comment (eoger) [inline components/places/src/import/fennec/bookmarks.rs]: We don't want to do `keyword` or `tags` below?

File: components/places/src/import/fennec/bookmarks.rs [hunk 2]
```diff
@@ -303,11 +303,11 @@ lazy_static::lazy_static! {
             isLocal
         )
         SELECT
-            normalize_root_guid(b.guid),
+            normalize_root_guid(sanitize_utf8(b.guid)),
             b.type,
-            (SELECT normalize_root_guid(p.guid) FROM fennec.bookmarks p WHERE p._id = b.parent),
+            IFNULL((SELECT normalize_root_guid(sanitize_utf8(p.guid)) FROM fennec.bookmarks p WHERE p._id = b.parent), 'unfiled_____'),
```
Comment (thomcc) [inline components/places/src/import/fennec/bookmarks.rs]: GUIDs have stricter requirements than just being valid UTF-8 (Must be printable ASCII) -- THis will result in guids we can't sync to the server.

File: components/places/src/import/fennec/bookmarks.rs (hunk 1 above)
Comment (mhammond) [reply components/places/src/import/fennec/bookmarks.rs]: We don't need tags because we drop them. I thought that was true for `keyword` too, but it's not - that is put into the moz_bookmarks_synced table. So tl;dr, yes, I should! Thanks!

File: components/places/src/import/fennec/bookmarks.rs (hunk 2 above)
Comment (mhammond) [reply components/places/src/import/fennec/bookmarks.rs]: > THis will result in guids we can't sync to the server.

That's handled by dogear. This will result in records we can at least read and hand off to dogear! IOW, any GUID touched by this function is already both (a) an invalid guid and (b) impossible for store.rs to read in the first place. This change just resolves (b), allowing our existing code to handle (a)
