### PR TITLE
Ensure engine state changes are acted on when there's a cached global state.

### LINKED ISSUE #2791: Changes to declined engines are ignored when we use cached state
As reported by @grigoryk, there's a recent regression caused by the fact that we now use some persisted state :(

In short, when we setup the state machine with the previous state [here](https://github.com/mozilla/application-services/blob/c759687a25ee5df12c2200fc74413b22971d965f/components/sync15/src/state.rs#L510) we don't check if there are engine state changes necessary. This shouldn't be too difficult to change (we can just discard most of that state), but testing will be a challenge (we can automate some tests in sync15, but will need to manually test the behaviour as used in Fenix)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-924)
┆Sprint: SYNC - end 2020-03-13

### PR DESCRIPTION
**Pull request by mhammond**
Fixes #2791

### CODE REVIEW

File: components/sync15/src/state.rs [hunk 1]
```diff
@@ -869,6 +869,9 @@ mod tests {
         let sm_seq_used_previous = vec!["WithPreviousState", "Ready"];
 
         // do the actual test.
+        // (clippy gets upset with `expected_states: &Vec<&str>` - wants it
+        // declared as `&[&str]` - which `assert_eq!()` then fails on!)
+        #[allow(clippy::ptr_arg)]
```
Comment (mhammond) [inline components/sync15/src/state.rs]: Not sure what the story is here!

Comment (linacambridge) [reply components/sync15/src/state.rs]: Try Clippy's suggestion with `assert_eq!(state_machine.sequence.as_slice(), expected_states)`?

File: components/sync15/src/state.rs [hunk 2]
```diff
@@ -852,6 +853,189 @@ mod tests {
...
+            );
+            assert_eq!(state_machine.sequence, *expected_states);
+        }
+
+        // and all the complicated setup...
+        let ts_metaglobal = 123_456;
+        let ts_keys = 145_000;
+        let root_key = KeyBundle::new_random().unwrap();
+        let keys = CollectionKeys {
+            timestamp: ServerTimestamp(123_400),
```
Comment (linacambridge) [inline components/sync15/src/state.rs]: Where does this old timestamp come into play? Or do we always overwrite it with `ts_keys`?

File: components/sync15/src/state.rs (hunk 1 above)
Comment (mhammond) [reply components/sync15/src/state.rs]: heh - so that got closer, and then complained about `&[...]` vs `[...]` - basically telling me to remove the leading `*` (which is necessary as written) - which worked. Then, it works without the `.as_slice()` too!

I'm not sure how many clippy bugs are in the above, but all's well that ends well :)

Thanks!

File: components/sync15/src/state.rs (hunk 2 above)
Comment (mhammond) [reply components/sync15/src/state.rs]: Thanks for noticing and it's a great question!

This is the timestamp we'll get back if we re-fetch the keys collection (which we do in most of the new tests). While the test doesn't care, I agree it's confusing, so I changed it to `ServerTimestamp(ts_keys + 1)` (which is hopefully enough of a hint)
