### PR TITLE
bug: store meta-data for push component in the database.

### LINKED ISSUE #905: Allow meta data storage for Push Component
Push does not currently persist needed information across restarts (e.g. UAID, Server Auth token, etc.).

### PR DESCRIPTION
**Pull request by jrconlin**
Push now stores `uaid` and the server secret `auth` in a table in the
push.db. the meta_data table allows any key/value data to be stored to
allow for additional future values (if needed).

Closes #905

### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - `cargo test --all` produces no test failures
  - `cargo clippy --all --all-targets --all-features` runs without emitting any warnings
  - `cargo fmt` does not produce any changes to the code
  - `./gradlew ktlint detekt` runs without emitting any warnings
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/master/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

File: components/push/storage/src/schema.sql [hunk 1]
```diff
@@ -10,4 +12,10 @@ CREATE TABLE IF NOT EXISTS push_record (
     native_id          TEXT,
     PRIMARY KEY (uaid, channel_id)
 );
+
 CREATE UNIQUE INDEX channel_id_idx ON push_record(channel_id);
+
+CREATE TABLE IF NOT EXISTS meta_data (
```
Comment (thomcc) [inline components/push/storage/src/schema.sql]: We probably want this to be

```
CREATE TABLE IF NOT EXISTS meta_data(
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
) WITHOUT ROWID;
```

to get the clustered index optimization.

(or even just `value NOT NULL` if non-text things will ever get stored there).

Also this is a simple enough migration that I strongly think we should just do it rather than asking our consumers to upgrade.

File: CHANGELOG.md [hunk 2]
```diff
@@ -10,11 +10,17 @@
...
+### What's fixed
+
+- PushAPI now stores some metadata information across restarts ([#905](https://github.com/mozilla/application-services/issues/905))
+
 ### Breaking changes
 
 - `mozilla.appservices.push.BridgeTypes` is now
   `mozilla.appservices.push.BridgeType`
 ([#885](https://github.com/mozilla/application-services/issues/885))
+- push.sqlite database has changed. Prior versions should be deleted.
```
Comment (thomcc) [inline CHANGELOG.md]: I feel that at a minimum we should delete the DB for consumers.

**Comment by jrconlin** [comment]
@pjenvey It's my understanding from @jonalmeida that there's no real data storage options for on the Kotlin side. In addition to this, I'm working on a version of Delivery manager that provides a storage mechanism for data associated with the ChannelID. 

It's also our understanding that profile changes effectively change all data because they point to a different android data directory. Containers would still use the same UAID, since incoming notifications effectively share the same User Agent.

I also tried to make the meta_data store fairly generic so that if we had to use multiple UAIDs, we could do crap like prefix key names or something. 

There still seem to be a lot of unknowns about how User Agents actually will operate and what features we'll be implementing, so simplifying to a base set seemed a better approach than designing for what may not happen.

File: components/push/storage/src/schema.sql (hunk 1 above)
Comment (jrconlin) [reply components/push/storage/src/schema.sql]: Updated the `update()` method to actually update. Not super happy with it, but hard to make something generic when there's only two versions.

File: CHANGELOG.md (hunk 2 above)
Comment (jrconlin) [reply CHANGELOG.md]: Or just do the work and actually upgrade.

File: components/push/storage/src/db.rs [hunk 3]
```diff
@@ -171,6 +175,24 @@ impl Storage for PushDb {
         )?;
         Ok(affected_rows == 1)
     }
+
+    fn get_meta(&self, key: &str) -> Result<Option<String>> {
+        // Get the most recent UAID (which should be the same value across all records,
+        // but paranoia)
+        let query = "SELECT value FROM meta_data where key = :key limit 1";
+        let mut statement = self.prepare(query)?;
+        let mut rows = statement.query_named(&[(":key", &key)])?;
```
Comment (thomcc) [inline components/push/storage/src/db.rs]: If you `use sql_support::ConnExt` this would be a lot shorter (something like `self.try_query_one(query, &[(":key", &key)], true)`) and would report query plans if built with --all-features.

File: components/push/storage/src/db.rs [hunk 4]
```diff
@@ -171,6 +175,23 @@ impl Storage for PushDb {
...
+            "SELECT value FROM meta_data where key = :key limit 1",
+            &[(":key", &key)],
+            true,
+        )
+        .map_err(|e| ErrorKind::StorageSqlError(e).into())
+    }
+
+    fn set_meta(&self, key: &str, value: &str) -> Result<()> {
+        let query = "INSERT or REPLACE into meta_data (key, value) values (:k, :v)";
+        self.execute_named(query, &[(":k", &key), (":v", &value)])?;
```
Comment (thomcc) [inline components/push/storage/src/db.rs]: Nit `execute_named_cached` (missed this last time, sorry).

File: components/push/subscriber/src/lib.rs [hunk 5]
```diff
@@ -66,7 +68,15 @@ impl PushManager {
         record.app_server_key = self.config.vapid_key.clone();
         record.native_id = Some(reg_token);
         self.store.put_record(&record)?;
-        // TODO: just return Record
+        // store the meta information if we've not yet done that.
+        if self.store.get_meta("uaid")?.is_none() {
```
Comment (thomcc) [inline components/push/subscriber/src/lib.rs]: Should we (do we?) have a transaction open here? I guess we only have a single connection, and so it shouldn' tmatter.

File: components/push/storage/src/schema.sql [hunk 6]
```diff
@@ -8,6 +9,16 @@ CREATE TABLE IF NOT EXISTS push_record (
     ctime              INTEGER  NOT NULL,
     app_server_key     TEXT,
     native_id          TEXT,
-    PRIMARY KEY (uaid, channel_id)
+    PRIMARY KEY
+(uaid, channel_id)
 );
+
+DROP INDEX IF EXISTS channel_id_idx;
 CREATE UNIQUE INDEX channel_id_idx ON push_record(channel_id);
```
Comment (thomcc) [inline components/push/storage/src/schema.sql]: Unless I'm missing something, `UNIQUE` implies the existence of a `UNIQUE INDEX`, so I don't think we need this.

**Comment by thomcc** [comment]
> @pjenvey It's my understanding from @jonalmeida that there's no real data storage options for on the Kotlin side.

Is this true? How do we persist the FxA state then?

**Comment by jonalmeida** [comment]
> > @pjenvey It's my understanding from @jonalmeida that there's no real data storage options for on the Kotlin side.
> 
> Is this true? How do we persist the FxA state then?

For the UAID, we can persist this but the argument was that, if each client needs to do this, wouldn't it be easier for the rust component to hide that away since it already does that?

For the Delivery Manager request, we have to store our own mapping of service to channelID on each client. Today this is a small list, but it can get quite large as we enable support for web push. For now, we're storing that on the Android side until we get a longer term solution.

**Comment by thomcc** [comment]
@jonalmeida Thanks, that makes sense. I agree it's better to persist here (especially since we already have a database to do it in) I was just confused since we were clearly persisting FxA on the android side, which the comment suggested was impossible.

**Comment by jrconlin** [comment]
Ah, good. The comment was borne of my own confusion as well. I thought that there was no (or very limited) db like storage available on the client side. My general fear was that I'd be creating a general preference storage system, which I really don't want to do. I'll fix up the comment and follow up with @jonalmeida about this offline.

File: components/push/subscriber/src/lib.rs (hunk 5 above)
Comment (jrconlin) [reply components/push/subscriber/src/lib.rs]: ideally, there would only be one "uaid". There's been some discussion about how this would be handled by containers (if/when they're brought over to mobile), but even then, having a single UAID may be the answer. UAID is more about delivery to a given device, channel about segregating to recipient processes. Same is true with the registration ID, to an extent, but that's generally initialized at app start and handed to us. The meta data is more a write once, read many store.

File: components/push/storage/src/db.rs (hunk 4 above)
Comment (jrconlin) [reply components/push/storage/src/db.rs]: crap, sorry, you're right.
