### PR TITLE
Check for Java version equals 8

### LINKED ISSUE #1459: Check Java version == 8 in verify-android-environment.sh
We should have caught this in the review of https://github.com/mozilla/application-services/pull/1371.
We need the JDK version to be **exactly** 8 as version 11 will fail to compile the Kotlin code.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-212)
┆Story Points: 2
┆Sprint: SYNC - 2019-10-24

### PR DESCRIPTION
**Pull request by eoger**
Fixes #1459.

### CODE REVIEW

File: libs/verify-android-environment.sh [hunk 1]
```diff
@@ -66,19 +66,10 @@ Please set the JAVA_HOME variable in your environment to match the
...
-          exit
-      fi
-    else
-      echo "ERROR: Incompatible java version"
-      exit 1
-    fi
+JAVA_VERSION=$("$JAVACMD" -version 2>&1 | grep -i version | cut -d'"' -f2 | cut -d'.' -f1-2)
+if [[ "${JAVA_VERSION}" != "1.8" ]]; then
+  echo "Incompatible java version: ${JAVA_VERSION}. JDK 8 must be installed."
+  exit
```
Comment (vladikoff) [inline libs/verify-android-environment.sh]: should this be `exit 1`?  

Also the terminal then hangs: 

image

and doesn't "exit the script"
