### PR TITLE
bug: Only call server subscribe on new channelID requests

### LINKED ISSUE #923: push should check existing uaid+channelids on subscription
Currently, push sends UAID+CHID to the server regardless of registered channels. This can produce an error. It should instead check to see if that combination is already defined and return existing information for the pair.

### PR DESCRIPTION
**Pull request by jrconlin**
Closes #923

### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - `cargo test --all` produces no test failures
  - `cargo clippy --all --all-targets --all-features` runs without emitting any warnings
  - `cargo fmt` does not produce any changes to the code
  - `./gradlew ktlint detekt` runs without emitting any warnings
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/master/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

File: components/push/src/subscriber.rs [hunk 1]
```diff
@@ -38,10 +38,24 @@ impl PushManager {
     }
 
     // XXX: make these trait methods
-    // XXX: should be called subscribe?
     pub fn subscribe(&mut self, channel_id: &str, scope: &str) -> Result<(RegisterResponse, Key)> {
         let reg_token = self.config.registration_id.clone().unwrap();
         let subscription_key: Key;
+        if let Some(uaid) = self.conn.uaid.clone() {
```
Comment (thomcc) [inline components/push/src/subscriber.rs]: We could probably postpone this clone until after get_record returns Some, but it also probably doesn't matter.

Comment (jrconlin) [reply components/push/src/subscriber.rs]: I was kinda debating that. The first run had just a check to see if `uaid.is_some()`, but then I realized I needed the value, and that to get it for `get_record` I needed to clone uaid to move it into reference, so I just kinda shrugged and went with the easier to read approach.

**Comment by jrconlin** [comment]
Fair point. If you're ever curious or suffer some random bout of insomnia: 

Push has two core parts, the User Agent side and the Server side. The general idea is "Hey, cool, if your servers ever want to send something to you, here's an endpoint and an encryption key." Their subscription servers take a message, encrypt it with the Key so our servers can't read it, then send it off to the endpoint. Our servers figure out which browser should get the message, and send it off. The Browser gets the message, hand it off to the UA, which decrypts the message and hands it off to whatever requested the subscription.

This patch fixes a kind of stupid bug on the UA side. The server is totally stupid about things because the less info we store the easier it is to scale. If you hand it a UAID (what identifies the browser) and ChannelID (what the UA uses to route to an app) it will gleefully generate a new endpoint. That's probably not what the caller really wanted. So instead, I just rebuild the response that would have been given from the data I already know about, and I don't send things over to the server.

Happy to go over push in more detail, but the Universe knows how much you've got to think about now and I'm happy not stuffing crap like that into your head unless you really want it.
