### PR TITLE
Fix duplication logic in logins migration

### LINKED ISSUE #4401: Ensure we correctly migrate multiple duplicate logins with empty username fields.
In #4400 there's a test that shows we allow an unlimited number of logins with duplicate infos so long as they have empty usernames. This smells like a bug, and because Desktop doesn't allow this, it almost certainly means we will fail to sync them.

FWIW, I verified Desktop's behaviour with:

```
diff --git toolkit/components/passwordmgr/test/unit/test_logins_change.js toolkit/components/passwordmgr/test/unit/test_logins_change.js
index 642faaa1b54a8..73f09d8c360aa 100644
--- toolkit/components/passwordmgr/test/unit/test_logins_change.js
+++ toolkit/components/passwordmgr/test/unit/test_logins_change.js
@@ -546,3 +546,9 @@ add_task(async function test_addLogins_badDates() {

   Services.logins.removeAllUserFacingLogins();
 });
+
+add_task(async function test_username_dupes() {
+  await LoginTestUtils.addLogin({username: "test", password: "pw"});
+  await LoginTestUtils.addLogin({username: "", password: "pw"});
+  await LoginTestUtils.addLogin({username: "", password: "pw"});
+});
```

Which fails with `"NS_ERROR_FAILURE: This login already exists."` and a stack that points to the last line of that test.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2749)
┆Epic: Logins update and sqlcipher migration
┆Fix Versions: Release 94
┆Sprint End Date: 2021-09-17

### PR DESCRIPTION
**Pull request by skhamis**
Fixes #4401 

Main focus was implementing a check for dupes before inserting into the local logins table (mirror is presumed to have dealt with this unless their sync was completely broken?)

### Pull Request checklist ###

- [ ] **Quality**: This PR builds and tests run cleanly
  - Note:
    - For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
    - If this pull request includes a breaking change, consider [cutting a new release](https://github.com/mozilla/application-services/blob/main/docs/howtos/cut-a-new-release.md) after merging.
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [ ] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/main/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

### CODE REVIEW

File: components/logins/src/migrate_sqlcipher_db.rs [hunk 1]
```diff
@@ -176,18 +178,18 @@ fn migrate_from_sqlcipher_db(
     encryption_key: &str,
 ) -> Result<MigrationMetrics> {
     // encrypt the username/password data
-    let encdec = EncryptorDecryptor::new(encryption_key)?;
+    let enc_dec = EncryptorDecryptor::new(encryption_key)?;
```
Comment (mhammond) [inline components/logins/src/migrate_sqlcipher_db.rs:181]: I think you should probably leave this as `encdec` - not that I have a strong preference for it, but literally every other instance of an `EncryptorDecryptor` is named `encdec` and there are currently zero named `enc_dec`. That will make this patch far far smaller and easier to read.

Comment (skhamis) [reply components/logins/src/migrate_sqlcipher_db.rs]: good call -- updated!

File: components/logins/src/migrate_sqlcipher_db.rs [hunk 2]
```diff
@@ -537,6 +548,16 @@ fn insert_local_login(conn: &Connection, local_login: &LocalLogin) -> Result<()>
         )";
 
     let login = &local_login.login;
+    let dec_login = &local_login.login.clone().decrypt(encdec)?;
+
+    match new_db.check_for_dupes(&login.guid(), &dec_login.entry(), &encdec) {
+        Ok(_) => {}
+        Err(e) => {
+            log::warn!("Duplicate {} ({}).", login.record.id, e);
+            // Should we record this as an error? or just silently ignore it
```
Comment (mhammond) [inline components/logins/src/migrate_sqlcipher_db.rs:557]: I think it might as well be recorded as an error - probably just have this return a bool?

File: components/logins/src/migrate_sqlcipher_db.rs [hunk 3]
```diff
@@ -537,6 +548,16 @@ fn insert_local_login(conn: &Connection, local_login: &LocalLogin) -> Result<()>
         )";
 
     let login = &local_login.login;
+    let dec_login = &local_login.login.clone().decrypt(encdec)?;
+
+    match new_db.check_for_dupes(&login.guid(), &dec_login.entry(), &encdec) {
```
Comment (mhammond) [inline components/logins/src/migrate_sqlcipher_db.rs:553]: I think `if let Err(e) = new_db.check_for_dupes(&login.guid(), &dec_login.entry(), &encdec) { ... }` ?

**Review by mhammond — APPROVED** [review]
Great, thanks Sammy!
