### PR TITLE
Short circuit if /invoke_command gets rate limited, until timeout period passes

### LINKED ISSUE #3231: [rust] Don't keep trying to send tabs if the server has rate-limited us
Both Fenix and Desktop have UI that supports sending multiple tabs at once. In fact the user can easily attempt to send themselves many hundreds or thousands of tabs by right-clicking the tab bar, choosing "select all tabs", and then "send `N` tabs to device". The send-tab infrastructure only supports sending one tab at a time. So sending `N` tabs gets turned into `N` calls to our `send_tab` function.

This does not work out well for large values of `N`.

The FxA server has some anti-abuse rate-limiting on the `/invoke_command` endpoint that underlies send-tab. It's generous, designed mostly to stop really obvious abuse or really serious client bugs that might otherwise bring down the service. So the first `n < N` tabs will be sent successfully, but all the rest will be rejected by the server with a `429` error.  This error appears to be silently dropped - not only does the user not receive feedback that some tabs failed to send, but the client keeps attempting to send all the remaining tabs!

We should, instead, _not_ do that, and refuse to attempt any more tab sending according to the backoff information given by the FxA server.

I believe this issue to exist on both Desktop and the rust fxa-client, but I'm filing it here because we might end up fixing it in Desktop by replacing its send-tab implementation with the rust component.

(By the way, there is also convenient UI for sending tabs to "all devices" as a single action. With `M` devices connected to your account this produces `N x M` individual `send_tab` calls. You can imagine how well that will work out for large values of both `N` and `M`...)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1391)
┆Story Points: 8
┆Epic: Trusted Send Tab Telemetry
┆Sprint: SYNC - end 2020-06-19

### PR DESCRIPTION
**Pull request by tarikeshaq**
### Pull Request checklist ###

- [x] **Quality**: This PR builds and tests run cleanly
  - `automation/all_tests.sh` runs to completion and produces no failures
  - Note: For changes that need extra cross-platform testing, consider adding `[ci full]` to the PR title.
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes a changelog entry in [CHANGES_UNRELEASED.md](../CHANGES_UNRELEASED.md) or an explanation of why it does not need one
  - Any breaking changes to Swift or Kotlin binding APIs are noted explicitly
- [x] **Dependencies**: This PR follows our [dependency management guidelines](https://github.com/mozilla/application-services/blob/master/docs/dependency-management.md)
  - Any new dependencies are accompanied by a summary of the due dilligence applied in selecting them.

fixes #3231

### CODE REVIEW

File: components/fxa-client/src/http_client.rs [hunk 1]
```diff
@@ -104,7 +106,17 @@ pub trait FxAClient {
     ) -> Result<HashMap<String, ScopedKeyDataResponse>>;
 }
 
-pub struct Client;
+enum FxAClientState {
```
Comment (vladikoff) [inline components/fxa-client/src/http_client.rs:109]: maybe this should be HttpClientState? 

We already have an FxAClientState

File: components/fxa-client/src/http_client.rs [hunk 2]
```diff
@@ -104,7 +106,17 @@ pub trait FxAClient {
...
+    Ok,
+    TimeOut {
+        time_out_end_duration: Duration,
```
Comment (vladikoff) [inline components/fxa-client/src/http_client.rs:112]: It could be that different endpoints we have will have different `retryAfter` limits. Is it possible to HashMap with a { 
endpoint: time_out_end_time
}
Example draft: `/commands` : `1591892366`

File: components/fxa-client/src/http_client.rs [hunk 3]
```diff
@@ -309,7 +333,36 @@ impl FxAClient for Client {
             .header(header_names::AUTHORIZATION, bearer_token(refresh_token))?
             .header(header_names::CONTENT_TYPE, "application/json")?
             .body(body.to_string());
-        Self::make_request(request)?;
+        // I am a really bad way to handle this
+        // I exist only because Tarik is experimenting :)
+        // I will be replaced with a better approach
+        match Self::make_request(request) {
```
Comment (vladikoff) [inline components/fxa-client/src/http_client.rs:339]: I think this is on the right track, looking at the code required to just short circuit the command route, we should just upgrade our `make_request` to be ubiquitous for other FxA endpoints.

File: components/fxa-client/src/http_client.rs [hunk 4]
```diff
@@ -395,25 +410,64 @@ impl Client {
...
-                Ok(json) => Err(ErrorKind::RemoteError {
-                    code: json["code"].as_u64().unwrap_or(0),
-                    errno: json["errno"].as_u64().unwrap_or(0),
-                    error: json["error"].as_str().unwrap_or("").to_string(),
-                    message: json["message"].as_str().unwrap_or("").to_string(),
-                    info: json["info"].as_str().unwrap_or("").to_string(),
-                }
-                .into()),
-                Err(_) => Err(resp.require_success().unwrap_err().into()),
+            match resp.status {
```
Comment (vladikoff) [inline components/fxa-client/src/http_client.rs:468]: nice this looks cleaner now 👍

File: components/fxa-client/src/http_client.rs [hunk 5]
```diff
@@ -482,7 +536,8 @@ pub fn send_authorization_request(
     let req = HawkRequestBuilder::new(Method::Post, auth_endpoint, auth_key)
         .body(serde_json::to_value(&auth_params)?)
         .build()?;
-    let resp: serde_json::Value = Client::make_request(req)?.json()?;
+    let client = Client::new();
```
Comment (vladikoff) [inline components/fxa-client/src/http_client.rs:539]: We are doing a `Client::new` in each request, is there a way of not doing that?

File: components/fxa-client/src/http_client.rs [hunk 6]
```diff
@@ -894,4 +951,164 @@ mod tests {
         };
         assert_eq!("{\"grant_type\":\"refresh_token\",\"client_id\":\"bar\",\"refresh_token\":\"foo\",\"scope\":\"bobo\",\"ttl\":123}", serde_json::to_string(&using_code).unwrap());
     }
+
+    #[test]
+    fn test_backoff() {
```
Comment (vladikoff) [inline components/fxa-client/src/http_client.rs:956]: thank you for creating these tests ! 🏅

File: components/fxa-client/src/http_client.rs (hunk 5 above)
Comment (tarikeshaq) [reply components/fxa-client/src/http_client.rs:539]: Yup! I can move those functions to be inside the Client impl and have the integration tests worry about creating the client 😄

File: components/fxa-client/src/http_client.rs (hunk 6 above)
Comment (tarikeshaq) [reply components/fxa-client/src/http_client.rs:956]: Tbh was kinda surprised that we don't have tests for everything else in this file 🙃

File: components/fxa-client/src/http_client.rs [hunk 7]
```diff
@@ -472,6 +526,10 @@ impl AuthorizationParameters {
     }
 }
 
+// Keeping those functions out of the FxAClient trate becouse functions in the
```
Comment (tarikeshaq) [inline components/fxa-client/src/http_client.rs:529]: Added those because of the Client::new() 😭 Tried adding the functions into the FxAClient trait, but since they are test only they made the mockiato upset and unable to compile tests. Any ideas, or would them hanging around here be okay?

Comment (vladikoff) [reply components/fxa-client/src/http_client.rs:529]: That's fine for now, this comment here will be helpful for the future 👍
