### PR TITLE
Throw RecordNotFoundError in PushManager.decrypt

### LINKED ISSUE #2282: [Push] Messages received after subscription is removed throws a StorageError
See https://github.com/mozilla-mobile/fenix/issues/6663#issuecomment-558765489.

When signing out on a device, we invoke unsubscribe for push immediately to to destroy that subscription. On Fenix, we're receiving a push message **after** the unsubscribe, so we fail at decrypting the push message.

The StorageError seems a bit too broad of an error type to catch (in case we end up hiding other bugs).

Possible solutions:
 - FxA should filter out sending the message the client that's disconnecting (we do something similar in the a-c [FxaDeviceConstellation](https://github.com/mozilla-mobile/android-components/blob/f5240c81c07691370c2dd985085e14017befb276/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt#L144)).
 - Use a different error type for clients to filter out as non-fatal.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-448)

### PR DESCRIPTION
**Pull request by eoger**
Fixes #2282. cc @jonalmeida

### CODE REVIEW

File: components/push/src/error.rs [hunk 1]
```diff
@@ -71,6 +74,7 @@ impl ErrorKind {
             ErrorKind::StorageSqlError(_) => 29,
             ErrorKind::MissingRegistrationTokenError => 30,
             ErrorKind::TranscodingError(_) => 31,
+            ErrorKind::RecordNotFoundError(_, _) => 32,
```
Comment (thomcc) [inline components/push/src/error.rs]: huh was there just no 32 before? Did we take it out leaving 33 alone or something? Weird.

Comment (eoger) [reply components/push/src/error.rs]: I'm pretty sure we removed it!
