### PR TITLE
Ensure we install temp tables/triggers on all connections, and not just new ones. Fixes #476

### LINKED ISSUE #476: After syncing, for all inserted places records visit_count_remote are 0; frecency is 0
After I sync, for all records in moz_places I see the following visit_count_remote=0, frecency=0. I do have records in moz_historyvisits, and their visit_types aren't of the excluded sort.

The incorrect frecency could just be a side-effect of a zero visit_count (since we gate frecency computation on the count being greater than 0).

visit_count_remote is supposed to be updated via a trigger, which shoudl fire on insertions into moz_historyvisits.

cc @thomcc @mhammond

### PR DESCRIPTION
**Pull request by thomcc**
Sadly, I accidentally pushed this to master a second ago before reverting. Oh well.

### CODE REVIEW

File: components/places/src/db/schema.rs [hunk 1]
```diff
@@ -236,6 +236,13 @@ pub fn init(db: &PlacesDb) -> Result<()> {
             )
         }
     }
+    log::debug!("Creating temp tables and triggers");
+    db.execute_all(&[
+        CREATE_TRIGGER_AFTER_INSERT_ON_PLACES,
+        &CREATE_TRIGGER_HISTORYVISITS_AFTERINSERT,
+        &CREATE_TRIGGER_HISTORYVISITS_AFTERDELETE,
+        &CREATE_TRIGGER_MOZPLACES_AFTERINSERT_REMOVE_TOMBSTONES,
```
Comment (grigoryk) [inline components/places/src/db/schema.rs]: This doesn't need to be a reference.
